apiVersion: v1
kind: Secret
metadata:
  name: omada-wg-config
  namespace: homelab
type: Opaque
stringData:
  wg0.conf: |
    [Interface]
    PrivateKey = CNoGVYX+jKNVJa6eoB/O9bIW7ig0wDkVtXeZnYoGB2A=
    Address = 10.27.79.7/32, fd89:d5a5:c5a7::7/64

    [Peer]
    PublicKey = bCMM98NXADnmRLvuW3JsZzRiLkxEOhdpUObv9/LnEDw=
    AllowedIPs = 10.27.79.0/24, 192.168.15.0/24, 192.168.2.0/24, fd89:d5a5:c5a7::7/64
    Endpoint = 178.128.95.212:51820
    PersistentKeepalive = 25
