prometheus:
  url: http://prometheus-operated.monitoring.svc.cluster.local
  port: 9090

rules:
  default: false
  custom:
    - seriesQuery: '{__name__=~"^simulated_user_load.*"}'
      resources:
        overrides:
          namespace: {resource: "namespace"}
          pod: {resource: "pod"}
      name:
        matches: "^(.*)"
        as: "simulated_user_load"
      metricsQuery: '<<.Series>>{<<.LabelMatchers>>}'
