apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homer-tls
  namespace: homelab
spec:
  secretName: homer-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - {{ base_domain }}
