---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  namespace: homelab
  labels:
    app: homer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homer
  template:
    metadata:
      labels:
        app: homer
    spec:
      containers:
        - name: homer
          image: ghcr.io/bastienwirtz/homer:latest
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "sed -i 's@</head>@<meta property=\"og:title\" content=\"Homelab | kenchlightyear.com\"><meta property=\"og:description\" content=\"Next-Gen Self-Hosting Infrastructure.\"><meta property=\"og:image\" content=\"https://home.kenchlightyear.com/assets/preview.png\"><meta name=\"twitter:card\" content=\"summary_large_image\"></head>@' /www/index.html"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /www/assets/config.yml
              subPath: config.yml
            - name: assets
              mountPath: /www/assets/custom.html
              subPath: custom.html
            - name: assets
              mountPath: /www/assets/preview.png
              subPath: preview.png
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: homer-config
        - name: assets
          configMap:
            name: homer-assets
