apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - homer-configmap.yaml
  - homer-deployment.yaml
  - homer-service.yaml

configMapGenerator:
  - name: homer-assets
    files:
      - index.html
      - preview.png
