apiVersion: v1
kind: ServiceAccount
metadata:
  name: hpa-app-workflow-sa
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hpa-app-deployer
  namespace: harvester-autoscaling-sim
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hpa-app-deployer-binding
  namespace: harvester-autoscaling-sim
subjects:
- kind: ServiceAccount
  name: hpa-app-workflow-sa
  namespace: argo
roleRef:
  kind: Role
  name: hpa-app-deployer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hpa-app-workflow-view-binding
subjects:
- kind: ServiceAccount
  name: hpa-app-workflow-sa
  namespace: argo
roleRef:
  kind: ClusterRole
  name: argo-workflows-view
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hpa-app-workflow-executor
  namespace: argo
rules:
- apiGroups: ["argoproj.io"]
  resources:
    - workflows/status
    - workflowtaskresults
    - workflowtaskresults/status
    - workflowtasksets
    - workflowtasksets/status
    - workflowartifactgctasks
    - workflowartifactgctasks/status
  verbs: ["get", "create", "update", "patch", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hpa-app-workflow-executor-binding
  namespace: argo
subjects:
- kind: ServiceAccount
  name: hpa-app-workflow-sa
  namespace: argo
roleRef:
  kind: Role
  name: hpa-app-workflow-executor
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflows-controller-patch
rules:
- apiGroups: ["argoproj.io"]
  resources:
    - workflows/status
    - workflowtaskresults
    - workflowtaskresults/status
    - workflowtasksets
    - workflowtasksets/status
    - workflowartifactgctasks
    - workflowartifactgctasks/status
  verbs: ["get", "create", "update", "patch", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/status", "pods/finalizers", "nodes"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflows-controller-patch-binding
subjects:
- kind: ServiceAccount
  name: argo-workflows-workflow-controller
  namespace: argo
roleRef:
  kind: ClusterRole
  name: argo-workflows-controller-patch
  apiGroup: rbac.authorization.k8s.io
