apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hpa-app-webhook-secret
  namespace: argo-events
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: hpa-app-webhook-secret
  data:
    - secretKey: webhook-token
      remoteRef:
        key: github-webhook
        property: token # User should ensure this property exists in Vault
