apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-registry-config
  namespace: argo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-registry-config # The final K8s secret name
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "registry.home.kenchlightyear.com": {
                "auth": "{{ printf "admin:%s" .password | b64enc }}"
              }
            }
          }
  data:
    - secretKey: password
      remoteRef:
        key: harbor # Relative to homelab mount
        property: admin-password # As seen in working homelab secret
