apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-pullsecret
  namespace: harvester-autoscaling-sim
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-pullsecret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "registry.home.kenchlightyear.com": {
                "username": "admin",
                "password": "{{ .password | toString }}",
                "auth": "{{ (printf "admin:%s" .password) | b64enc }}"
              }
            }
          }
  data:
    - secretKey: password
      remoteRef:
        key: harbor
        property: admin-password
